server:
  port: 8081
logging:
  level:
    root: ERROR
    org:
      springframework:
        beans: ERROR
        security: ERROR
        web: ERROR
      hibernate: ERROR
      apache:
        commons:
          dbcp2: ERROR

  pattern:
    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
my:
  name: forezp
  age: 12
