apiVersion: apps/v1
kind: Deployment
metadata:
  name: zgtesting-1
  namespace: ossm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zgtesting-1
  template:
    metadata:
      labels:
        app: zgtesting-1
    spec:
      containers:
        - name: zgtesting-1
          image: yzgang1976/zgtesting_1:latest
          ports:
            - containerPort: 8081
              protocol: TCP
        - name: host-info-service
          image: yzgang1976/host-info-service:latest
          ports:
            - containerPort: 8082
              protocol: TCP
