apiVersion: apps/v1
kind: Deployment
metadata:
  name: zgtesting-1
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zgtesting-1
  template:
    metadata:
      labels:
        app: zgtesting-1
    spec:
      containers:
        - name: zgtesting-1
          image: yzgang1976/zgtesting_1:0.3
          ports:
            - containerPort: 8081
              protocol: TCP
