apiVersion: v1
kind: Service
metadata:
  name: zgtesting-1
  namespace: default
  labels:
    app: zgtesting-1
spec:
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 31081
  selector:
    app: zgtesting-1
  type: NodePort